In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from PIL import Image
from einops import rearrange
import requests
import io
import json
from tqdm import tqdm
import mediapy as media
import jax
import numpy as np

In [15]:
run_dir = Path('mini_agent_stats') # Path('baselines/session_ebdfe818')
# original session_e41c9eff, main session_4da05e87, extra session_e1b6d2dc

In [16]:
dfs = []
for run in tqdm(run_dir.glob('*.gz')):
    tdf = pd.read_csv(run, compression='gzip')
    dfs.append(tdf[tdf['map'] != 'map'])

5it [01:31, 18.33s/it]


In [8]:
np.array([2,3])

array([2, 3])

In [5]:
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [6]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [17]:
poke_id_to_name = {
    177: "Squirtle",
    255: "None",
    0: "None",
    165: "Rattata",
    36: "Pidgey",
    179: "Wartortle",
    150: "Pidgeotto",
    112: "Weedle",
    113: "Kakuna",
    133: "Magikarp",
    169: "Geodude",
    107: "Zubat",
    109: "Paras",
    100: "Jigglypuff",
    84: "Pikachu",
    124: "Metapod",
    4: "Clefairy"
}

In [ ]:
# find time spent holding each pokemon
all_poke_counts = []
for df in dfs:
    size = len(df)
    count = 0
    cur_run_idx = 0
    for step in tqdm(df['ptypes']):
        run_idx = count // size
        if run_idx == cur_run_idx:
            cur_run = set()
            cur_run_idx += 1
        
        pokes = json.loads(step)
        for p in pokes:
            pname = poke_id_to_name[p]
            cur_run.add(pname)
        count += 1
        

In [20]:
len(dfs[0])/610

16385.0

In [25]:
(2*16385-1) // 16385

1

In [26]:
dfs[0].keys()

Index(['Unnamed: 0', 'step', 'x', 'y', 'map', 'pcount', 'levels', 'ptypes',
       'hp', 'frames', 'deaths', 'badge', 'event', 'healr'],
      dtype='object')